// <auto-generated />
using System;
using System.Linq;
using API_Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Migrations;

namespace API_Persistencia.Migrations
{
    [DbContext(typeof(ConexionDB))]
    [Migration("20230316144558_add-actividad-entity")]
    public partial class addActividadEntity : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "actividadId",
                table: "Usuario",
                type: "nvarchar(450)",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_Usuario_actividadId",
                table: "Usuario",
                column: "actividadId",
                unique: true,
                filter: "[actividadId] IS NOT NULL");

            migrationBuilder.AddForeignKey(
                name: "FK_Usuario_Actividad_actividadId",
                table: "Usuario",
                column: "actividadId",
                principalTable: "Actividad",
                principalColumn: "actividadId",
                onDelete: ReferentialAction.Restrict);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Usuario_Actividad_actividadId",
                table: "Usuario");

            migrationBuilder.DropIndex(
                name: "IX_Usuario_actividadId",
                table: "Usuario");

            migrationBuilder.DropColumn(
                name: "actividadId",
                table: "Usuario");
        }
    }

    // Add more migration classes for other entities here...

    [DbContext(typeof(ConexionDB))]
    [Migration("20230316150000_add-tokens")]
    public partial class addTokens : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "refreshToken",
                table: "Usuario",
                type: "nvarchar(max)",
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "refreshTokenExpiryTime",
                table: "Usuario",
                type: "datetime2",
                nullable: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "refreshToken",
                table: "Usuario");

            migrationBuilder.DropColumn(
                name: "refreshTokenExpiryTime",
                table: "Usuario");
        }
    }
}
